'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Reservas
    Public Property id As Integer
    Public Property codigoReserva As Nullable(Of Integer)
    Public Property fechaReserva As Nullable(Of Date)
    Public Property idCliente As Nullable(Of Integer)
    Public Property idVendedor As Nullable(Of Integer)
    Public Property costo As Nullable(Of Double)
    Public Property precioVenta As Nullable(Of Double)
    Public Property idVehiculoCiudad As Nullable(Of Integer)
    Public Property idCiudad As Nullable(Of Integer)
    Public Property idPais As Nullable(Of Integer)

    Public Overridable Property Clientes As Clientes
    Public Overridable Property Vendedor As Vendedor

End Class
