'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TuricorBDEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TuricorBDEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Clientes() As DbSet(Of Clientes)
    Public Overridable Property Reservas() As DbSet(Of Reservas)
    Public Overridable Property Vendedor() As DbSet(Of Vendedor)

End Class
